### PR TITLE
Compiling with openssl

### PR DESCRIPTION
**Pull request by tfmoraes**

### CODE REVIEW

**Comment by fo42740** [comment]
Hello @tfmoraes, thank you for this improvement in python-gdcm ! 
How can I help you testing/merging this modification ? 
Should I run pip install python-gdcm and test the crypto part ? 
I am on macOS Monterey

**Comment by fo42740** [comment]
I have tried it on my Mac with x86_64 and now I can de-identify and re-identify but I often have segmentation faults appearing randomly when de-identifying. 
I have tried with Python 3.6 and 3.8 and I have the same results, it works perfectly to re-identify but the de-identify part often crashes at the line ano.BasicApplicationLevelConfidentialityProfile()
I use the same code as in /GDCM/Examples/Csharp/BasicAnonymiser.cs 
Do you have an idea where it could come from ?
Thank you

**Comment by tfmoraes** [comment]
This is also happening if you use GDCM from Homebrew?

**Comment by fo42740** [comment]
No I could install gdcm with HomeBrew I can use gdcmanon without any problem. I guess it uses the same functions.
With python I use an environnement created with conda and then I install the wheel. I’ll try without conda environnement to see if it can come from there but I don’t see why.

**Comment by tfmoraes** [comment]
@fo42740 `python-gdcm` also install `gdcmanon` and other `GDCM` applications.

**Comment by fo42740** [comment]
@tfmoraes Indeed I can also use gdcmanon after installing python-gdcm. gdcmanon works well with the installation of python-gdcm but unless I am missing something, I can't use gdcmanon inside a python script (I could use "subprocess" but I'd rather not). That's why I tried to use gdcm.Anonymizer but got problem with the crypto part

**Comment by fo42740** [comment]
@tfmoraes Actually I have troubles using gdcmanon after installing python-gdcm with your wheels. 
I have the following error "Could not load XML file from specified path". And I don't have it if I use GDCM from HomeBrew (I didn't see it at first because GDCM was installed with Homebrew in another environnement).
If I don't use your new wheels and make only pip install python-gdcm I get the error "Requested cryptographic library not configured" so crypto seems ok with me on this version.

**Comment by fo42740** [comment]
@tfmoraes, I found a similar topic here : https://sourceforge.net/p/gdcm/mailman/message/32356380/
I am not very familiar with Xcode building so I don't know if something is missing on my Mac.
This subject doesn't seem to the same as openssl but I can't check the crypto part then.

**Comment by tfmoraes** [comment]
I think it's needed to add some missing XML files in the wheel.

**Comment by tfmoraes** [comment]
@fo42740 now I'm including the needed XML files and it's also compiling with OpenSSL support on Mac (M1) and Windows. Please, could you test if it working?

**Comment by fo42740** [comment]
@tfmoraes , I have tested it on Mac and gdcmanon is working perfectly !
I still have my problem of segmentation fault while using Anonymizer function in Python.
Maybe it comes from what I do but the function BasicApplicationLevelConfidentialityProfile() crashes randomly (file attached).
I tried your wheels in conda environnement with macOS Monterey, macOS Catalina and Windows 7 and I got the same segmentation faults. I'll try next week on CentOs to see if I have the same result.
[ano_GDCM.py.zip](https://github.com/tfmoraes/python-gdcm/files/8047157/ano_GDCM.py.zip)

**Comment by tfmoraes** [comment]
I tried on the Ubuntu and it worked without a segfault. I'll try with a Mac M1

**Comment by tfmoraes** [comment]
I tried on macOS 12.2 (M1) and the segfault it's happening using the wheels generated here and the `GDCM` installed by Brew. I'll merge this and submit the generated wheels to Pypi.

**Comment by fo42740** [comment]
That’s perfect, thank you !

**Pull request merged**
