### PR TITLE
Fix wheel builds on Windows for Python 3.10

### PR DESCRIPTION
**Pull request by scaramallion**
* Fix broken path to Python 3.10 lib

### CODE REVIEW

**Comment by tfmoraes** [comment]
Thanks @scaramallion I tested here on Windows 10 with python3.9 and python3.10, worked in both. I tested on Ubuntu with python3.9 and worked too. Thanks again!

**Comment by tfmoraes** [comment]
I'll run CI before the merge.

**Comment by tfmoraes** [comment]
I uploaded the Window Python3.10 wheels to Pypi.

**Comment by scaramallion** [comment]
Awesome, thanks

**Pull request merged**
