### PR TITLE
Gdcm applications

### PR DESCRIPTION
**Pull request by tfmoraes**

### CODE REVIEW

**Comment by JSousa-UoL** [comment]
Your latest commit allowed a successful build it seems. How exactly can I test this? I can get your branch and the files, but I don't know exactly how I can help you.

Should I run `python setup.py install` or should I do `pip install python-gdcm`? Or should I run a completely different command?

**Comment by tfmoraes** [comment]
I uploaded all wheel files generated here https://we.tl/t-HK80R6HP0w

**Comment by JSousa-UoL** [comment]
I tested for Windows Python 3.7 and the pip install of the wheel when ok and it's working fine overall. I still haven't found the apps I'm looking for, but something should have happened since the CMAKE flag was switched to ON.
Feel free to merge this PR and thank you so much for doing all this effort so far @tfmoraes

**Comment by tfmoraes** [comment]
They will be inside gdcm folder in the python site-packages. Inside the scripts in python instalation will be the wrappers I created to call the GDCM applications. Unfortunately in Windows it doesn't work this way but in MacOS and Linux the wrappers will be in the PATH then it will be possible to call the GDCM applications very easily.

**Pull request merged**
